// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    
		int n = Integer.parseInt(args[0]);

		int greaerCount = 0;
		int leqCount =0;

		for (int i = 0; i < n; i++) {
			double r = Math.random();
			if (r > 0.5) {
				greaerCount++;
			} else {
				leqCount++;
			}
		}
		System.out.println("> 0.5: " + greaerCount + " times");
		System.out.println("<= 0.5: " + leqCount + " times");

		if (leqCount == 0) {

			System.out.println("Ratio: undefined");
		} else {
			double ratio = (double) greaerCount / leqCount;
			System.out.println("Ratio: " + ratio);
			
		}
	}
}
